
@startuml

!theme _none_
top to bottom direction
skinparam linetype ortho

class DirectoryAttributeEntityDelete
interface DirectoryAttributeEntityService << interface >>
class DirectoryAttributeEntityServiceImpl
interface DirectoryAttributeService << interface >>
class DirectoryAttributeServiceImpl
class DirectoryAttributeUtils
class DirectoryFunctionsMapper
class node0 as "package  ru.sibintek.eksc.directory.directoryAttribute.service.chain" << package >>
class node2 as "package  ru.sibintek.eksc.directory.directoryAttribute.service.stream" << package >>

DirectoryAttributeEntityServiceImpl  -[#008200,dashed]-^  DirectoryAttributeEntityService     
DirectoryAttributeServiceImpl        -[#008200,dashed]-^  DirectoryAttributeService           
@enduml
