
@startuml

!theme _none_
title Service diagram
left to right direction
skinparam linetype ortho
skinparam classFontSize 14
skinparam classAttributeFontSize 12

class ConcatNoteService {
  - concatZoNoteService: ConcatZoNoteService
  - concatZdNoteService: ConcatZdNoteService
  - concatRoleNoteService: ConcatRoleNoteService
  - concatPasswordNoteService: ConcatPasswordNoteService
}
class ConcatTopicService {
  - concatPasswordTopicService: ConcatPasswordTopicService
  - concatRoleTopicService: ConcatRoleTopicService
  - concatZoTopicService: ConcatZoTopicService
  - concatZdTopicService: ConcatZdTopicService
}
class ConcatUrlService {
  ~ start: StringBuilder
  - concatZdUrl: ConcatZdUrl
  - concatZoUrl: ConcatZoUrl
}
class RegistryNotificationService {
  - receiversDtoDao: ReceiversDtoDao
  - concatUrlService: ConcatUrlService
  - concatNoteService: ConcatNoteService
  - concatTopicService: ConcatTopicService
  - userLoginJwt: UserLoginJwt
}
annotation Service << annotation >>

ConcatNoteService            -[#999900,dotted]-  Service                     
ConcatTopicService           -[#999900,dotted]-  Service                     
ConcatUrlService             -[#999900,dotted]-  Service                     
RegistryNotificationService  -[#999900,dotted]-  Service                     
@enduml
