@startuml

[*] --> DRAFT

DRAFT --> CREATED : SAVED

CREATED --> CHECK : CHECK

CHECK --> REJECTAPPROVAL: REJECTEDAPPROVAL

REJECTAPPROVAL --> CHECK: CHECK

CHECK --> APPROVE: APPROVED

APPROVE --> ACCEPT: ACCEPTED

APPROVE --> REJECTACCEPTANCE: REJECTEDACCEPTANCE

REJECTACCEPTANCE --> CHECK: CHECK

ACCEPT --> [*]

ACCEPT --> DELETE: DELETED

DELETE --> [*]

@enduml