
@startuml

[*] --> DRAFT
DRAFT --> CREATED : SAVED
CREATED --> CHECK : TO_CHECK
CHECK --> CORRECT: NO_APPROVE
CORRECT --> CHECK : CHECK_N_APPROV
CHECK --> APPROVE : APPROVING
APPROVE --> REJECT : NO_APPROVE
REJECT --> CHECK : CHECK_N_APPROVE
APPROVE --> COMPLETE : APPROVE
COMPLETE --> [*]
COMPLETE --> TECH_DELETED : TECH_DEL
TECH_DELETED --> [*]

@enduml