version: "3.5"

services:

  eksc-nginx:
    container_name: eksc-nginx
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    build:
      context: ./
      dockerfile: ./nginx.Dockerfile
    # network_mode: host
    ports:
      - "80:80"
    networks:
      - eksc-network
    profiles:
      - base

  eksc-zdocs:
    image: nginx:alpine
    container_name: eksc-zdocs
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    build:
      context: ../../1147_zdocs
      dockerfile: ../1147_config/docker/zdocs.Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./data/eksc/zdocs/storage:/usr/share/nginx/html/storage
      - ./data/eksc/zdocs/data:/usr/share/nginx/html/documents
    networks:
      - eksc-network
    profiles:
      - base

  plantuml:
    image: seaf/plantuml-server:jetty
    container_name: plantuml
    ports:
      - "8079:8080"
    networks:
      - eksc-network

#Docker Networks
networks:
  eksc-network:
    driver: bridge
