
@startuml

scale 0.5
left to right direction
skinparam linetype ortho
'skinparam classAttributeIconSize 0
skinparam classAttributeFontSize 12

<style>
classDiagram {
  class {
      header {
        FontSize 14
        FontStyle bold
      }
  }
}
</style>

package "Museumium" {

    !include account_class.puml
    !include checklist_item_class.puml
    !include exhibit_class.puml
    !include exhibition_class.puml
    !include location_class.puml
    !include museum_class.puml
    !include museum_photo_class.puml
    !include news_class.puml
    !include ticket_class.puml
    !include user_class.puml
    !include user_photo_class.puml
    !include visit_class.puml

    class VisitService {

    }
    User -- UserPhotoService: uses
    User -- UserService: uses
    User -- AccountService: uses

    AccountService "1" -[dashed]-> "1" Account: provides
    UserPhotoService "1" -[dashed]-> "0..*" UserPhoto: provides

    MuseumService "1" -[dashed]-> "0..*" Museum: provides
    MuseumService --> MuseumPhotoService: uses
    MuseumService --> ExhibitionService: uses

    VisitService "1" -[dashed]-> "0..*" Visit: provides
    VisitService --> ChecklistService: uses
    VisitService --> AccountService: uses
    VisitService --> TicketService: uses
    VisitService -> ExhibitionService: uses

    ChecklistService "1" -[dashed]-> "0..*" ChecklistItem: provides

    ExhibitionService "1" -[dashed]-> "0..*" Exhibition: provides
    ExhibitionService --> ExhibitService: uses

    ExhibitService "1" -[dashed]-> "0..*" Exhibit: provides
    ExhibitService --> LocationService: uses

    TicketService "1" -[dashed]-> "0..*" Ticket: provides

    LocationService "1" -[dashed]---> "0..*" Location: provides

    MuseumPhotoService "1" -[dashed]left-> "0..*" MuseumPhoto: provides

    NewsService "1" -[dashed]left-> "0..*" News: provides
    NewsService --> MuseumService: uses

'    Accounts "1" -- "0..*" Visits
'    Accounts "1" -- "0..*" AccountNews
'    Museums "1" -- "0..*" MuseumExhibitions
'    Museums "1" -- "0..*" MuseumPhotos
'    Exhibitions "1" -- "0..*" MuseumExhibitions
'    Exhibitions "1" -- "0..*" ExhibitionsExhibits
'    Visits "1" -- "0..*" Tickets
'    Visits "1" -- "0..*" ChecklistItems
'    Visits "1" -- "0..1" Routes
'    Exhibits "1" -- "0..*" ExhibitionsExhibits
'    Exhibits "1" -- "0..*" ExhibitLocation
'    Locations "1" -- "0..*" ExhibitLocation
'    News "1" -- "0..*" AccountNews
}
@enduml