

@startsalt
{
{T!
+Название функции                                   | Краткое описание

+ Просмотр реестра НСИ                              | asdf
++ Просмотр структуры справочника                   | asdf
+++ Смена даты отображения                          | asdf
+++ Поиск по атрибутам элементов справочника        | asdf
++++ Результаты поиска по элементам справочника     | asdf
++++ Навигация по найденным атрибутам               | asdf
+++ Раскрытие иерархии                              | asdf
++++ Скрытие иерархии                               | asdf
+++ Отметка / снятие чекбоксов                      | asdf
++ Установка фильтра для атрибутов                  | asdf
+++ Отбор атрибутов                                 | asdf
+++ Изменение порядка отображения атрибутов         | asdf
+++ Восстановление порядка по умолчанию             | asdf
+++ Загрузка значений атрибутов                     | asdf
+++ Выбор значений атрибутов                        | asdf
+++ Сброс значений атрибутов                        | asdf
+++ Применение фильтра                              | asdf
++ Просмотр записей справочника                     | asdf
+++ Просмотр карточки записи                        | asdf
++++ Просмотр истории изменений атрибутов записи    | asdf

}
}
@endsalt
